"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CheckCircle2,Mail,RefreshCw,ShieldCheck} from "lucide-react";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
export default function Config(){
 const [email,setEmail]=useState<string|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}const {data}=await supabase.from("google_connections").select("google_email").eq("user_id",user.id).maybeSingle();setEmail(data?.google_email||null);setLoading(false)})()},[]);
 function connect(){const client=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;if(!client){alert("A integração Google ainda precisa das credenciais OAuth do Google Cloud.");return}const redirect=location.origin+"/api/google/callback";const scope=encodeURIComponent("openid email https://www.googleapis.com/auth/gmail.readonly");const url="https://accounts.google.com/o/oauth2/v2/auth?client_id="+encodeURIComponent(client)+"&redirect_uri="+encodeURIComponent(redirect)+"&response_type=code&access_type=offline&prompt=consent&scope="+scope;location.href=url}
 return <main className="auth"><section className="auth-card"><button className="ghost back" onClick={()=>location.href="/leads"}><ArrowLeft size={17}/> Voltar</button><div className="brand"><div className="brand-icon"><Mail size={24}/></div><div><strong>Conectar Google</strong><span>Caixa de entrada dos leads</span></div></div><h1>{email?"Google conectado":"Conectar e-mail"}</h1><p className="muted">Conecte o Gmail que recebe os leads. O sistema vai identificar o destinatário, importar os campos do e-mail e gerar uma notificação imediatamente.</p><div className="terms-box"><div className="connect-row"><ShieldCheck size={22}/><div><strong>Leitura somente</strong><p>O sistema precisa apenas ler os e-mails de leads. Não envia, apaga ou altera suas mensagens.</p></div></div>{email&&<div className="connected"><CheckCircle2 size={18}/><span>{email}</span></div>}</div><button onClick={connect}>{email?"Reconectar Google":"Conectar Google"} <RefreshCw size={18}/></button><p className="tiny">A conexão usa OAuth do Google e o acesso fica limitado à leitura da caixa de entrada.</p></section></main>}