"use client";
import { useEffect,useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { CheckCircle2, ShieldCheck } from "lucide-react";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
export default function Terms(){
 const [user,setUser]=useState<any>(null);const [accepted,setAccepted]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}setUser(user);const {data}=await supabase.from("profiles").select("google_terms_accepted_at").eq("id",user.id).maybeSingle();if(data?.google_terms_accepted_at)location.href="/leads";setLoading(false)})()},[]);
 async function accept(){setLoading(true);const {error}=await supabase.from("profiles").update({google_terms_accepted_at:new Date().toISOString()}).eq("id",user.id);if(!error)location.href="/leads";else setLoading(false)}
 return <main className="auth"><section className="auth-card terms"><div className="brand"><div className="brand-icon"><ShieldCheck size={24}/></div><div><strong>Configuração inicial</strong><span>Antes de começar a receber leads</span></div></div><h1>Conectar e começar</h1><p className="muted">Para usar o painel, confirme que você aceita os termos necessários para a integração com os serviços do Google e o recebimento dos leads no seu e-mail.</p><div className="terms-box"><h3>O que será feito</h3><p>O sistema usará o e-mail cadastrado para identificar os leads destinados a você e organizar essas informações no painel.</p><label className="check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Li e aceito os termos para utilizar o recebimento e gerenciamento de leads.</span></label></div><button disabled={!accepted||loading} onClick={accept}>{loading?"Carregando...":"Aceitar e começar"} <CheckCircle2 size={18}/></button></section></main>}