"use client";
import { useEffect,useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { LogOut,Search,UserRound,RefreshCw,Bell,Check } from "lucide-react";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
type Lead={id:string;name:string|null;phone:string|null;plate:string|null;taxi_app:string|null;received_at:string|null;status:string};
type Notice={id:string;lead_id:string|null;title:string;message:string;read_at:string|null;created_at:string;user_id:string};
export default function Leads(){
 const [leads,setLeads]=useState<Lead[]>([]),[notices,setNotices]=useState<Notice[]>([]),[loading,setLoading]=useState(true),[user,setUser]=useState<any>(null),[q,setQ]=useState(""),[open,setOpen]=useState(false);
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/";return}setUser(user);
  const [{data:ls},{data:ns}]=await Promise.all([supabase.from("leads").select("id,name,phone,plate,taxi_app,received_at,status").order("received_at",{ascending:false}),supabase.from("notifications").select("id,lead_id,title,message,read_at,created_at,user_id").order("created_at",{ascending:false}).limit(30)]);setLeads(ls||[]);setNotices(ns||[]);setLoading(false)}
 useEffect(()=>{load();const channel=supabase.channel("notifications-live").on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications"},async payload=>{const n=payload.new as Notice;const {data:{user}}=await supabase.auth.getUser();if(n.user_id!==user?.id)return;setNotices(x=>[n,...x].slice(0,30));setOpen(true);if("Notification"in window&&Notification.permission==="granted")new Notification(n.title,{body:n.message});load()}).subscribe();return()=>{supabase.removeChannel(channel)}},[]);
 async function enablePush(){if(!("serviceWorker"in navigator)||!("PushManager"in window))return;const permission=await Notification.requestPermission();if(permission!=="granted")return;const reg=await navigator.serviceWorker.register("/sw.js");const keyRes=await fetch("/api/push/vapid-public");const {publicKey}=await keyRes.json();if(!publicKey)return;const b64=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=="),c=>c.charCodeAt(0));let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(publicKey)});const {data:{session}}=await supabase.auth.getSession();if(session)await fetch("/api/push/subscribe",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify(sub.toJSON())})}
 async function enableNotifications(){await enablePush();if("Notification"in window&&Notification.permission==="granted")setOpen(true)}
 async function markRead(id:string){const now=new Date().toISOString();await supabase.from("notifications").update({read_at:now}).eq("id",id);setNotices(x=>x.map(n=>n.id===id?{...n,read_at:now}:n))}
 const filtered=leads.filter(x=>[x.name,x.phone,x.plate,x.taxi_app].join(" ").toLowerCase().includes(q.toLowerCase())),unread=notices.filter(n=>!n.read_at).length;
 return <main className="app"><header><div className="brand"><div className="brand-icon"><UserRound size={21}/></div><div><strong>Painel de Leads</strong><span>Leads recebidos por e-mail</span></div></div><div className="header-actions"><button className="bell" onClick={()=>{setOpen(!open);enableNotifications()}}><Bell size={18}/>{unread>0&&<b>{unread}</b>}</button><span>{user?.email}</span><button className="ghost" onClick={async()=>{await supabase.auth.signOut();location.href="/"}}><LogOut size={17}/> Sair</button></div></header>
 {open&&<aside className="notifications"><div className="notif-head"><strong>Notificações</strong><button className="close" onClick={()=>setOpen(false)}>×</button></div>{notices.length===0?<div className="notif-empty">Nenhuma notificação.</div>:notices.map(n=><div className={"notice-item "+(!n.read_at?"unread":"")} key={n.id} onClick={()=>markRead(n.id)}><div><strong>{n.title}</strong><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString("pt-BR")}</small></div>{!n.read_at&&<Check size={16}/>}</div>)}</aside>}
 <section className="content"><div className="page-head"><div><h1>Meus Leads</h1><p>Acompanhe os leads que chegaram para você.</p></div><button className="ghost" onClick={load}><RefreshCw size={17}/> Atualizar</button></div><div className="toolbar"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome, telefone, placa..."/></div>
 <div className="table-wrap">{loading?<div className="empty">Carregando leads...</div>:filtered.length===0?<div className="empty">Nenhum lead encontrado.</div>:<table><thead><tr><th>Lead</th><th>Telefone</th><th>Placa</th><th>Taxi/App</th><th>Recebido</th><th>Status</th></tr></thead><tbody>{filtered.map(l=><tr id={"lead-"+l.id} key={l.id}><td><strong>{l.name||"Sem nome"}</strong></td><td>{l.phone||"—"}</td><td>{l.plate||"—"}</td><td>{l.taxi_app||"—"}</td><td>{l.received_at?new Date(l.received_at).toLocaleString("pt-BR"):"—"}</td><td><span className={"status "+l.status}>{l.status.replace("_"," ")}</span></td></tr>)}</tbody></table>}</div></section></main>
}